#!/usr/bin/env bash
# Emit a state-mate `<net>.deployed.yaml` sibling from this migration's freshly-deployed addresses.
#
# Usage: write-deployed-yaml.sh OUT_PATH POOL TRIGGER RECEIVER
#
# The three addresses are the ONLY contracts this migration deploys (OraclePool, SyncTrigger,
# CREReceiver) — so this file is always regenerable from a deploy broadcast, with no pre-existing
# seed. The pre-existing CustomSender proxy/impl + ProxyAdmin are NOT here: they are fixed external
# facts pinned in config/state/l2-<net>.inputs.yaml (externals:), cross-checked by verify-constants-sync.
# Every value is validated as a non-zero 0x+40hex address and checksummed before writing — the
# state-mate `.deployed` loader rejects `null`/placeholder, so we fail early here with a clear message.
set -euo pipefail

if [[ "$#" -ne 4 ]]; then
  echo "write-deployed-yaml: expected 4 args (OUT POOL TRIGGER RECEIVER), got $#" >&2
  exit 1
fi
command -v cast >/dev/null 2>&1 || { echo "write-deployed-yaml: missing required command: cast" >&2; exit 1; }

out="$1"; shift
labels=(l2OraclePool l2SyncTrigger l2CreReceiver)
addrs=("$@")

declare -a checksummed
for i in "${!addrs[@]}"; do
  a="${addrs[$i]}"
  if [[ ! "$a" =~ ^0x[0-9a-fA-F]{40}$ || "$a" == 0x0000000000000000000000000000000000000000 ]]; then
    echo "write-deployed-yaml: ${labels[$i]} is not a valid non-zero address: '${a:-<unset>}'" >&2
    exit 1
  fi
  checksummed[$i]="$(cast to-check-sum-address "$a")"
done

{
  echo "---"
  echo "# GENERATED by 'just deploy-test' — review and commit alongside the migration; do not hand-edit."
  echo "# The three Stage-1 deploy outputs (OraclePool, SyncTrigger, CREReceiver) — the only contracts this"
  echo "# migration deploys. The pre-existing CustomSender proxy/impl + ProxyAdmin are external facts in"
  echo "# config/state/l2-<net>.inputs.yaml (externals:), NOT here. state-mate concatenates this file"
  echo "# (anchors first) ahead of the wiring <net>.yaml so the *aliases resolve."
  echo "deployed:"
  echo "  l1: [] # L2 configs check no L1 contracts (the L1 receiver is verified by l1.yaml)."
  echo "  l2:"
  for i in "${!labels[@]}"; do
    printf '    - &%s "%s"\n' "${labels[$i]}" "${checksummed[$i]}"
  done
} > "$out"

echo "Wrote $out"
