#!/usr/bin/env bash
# Emit a state-mate `<net>.deployed.yaml` sibling from this migration's freshly-deployed addresses.
#
# Usage: write-deployed-yaml.sh OUT_PATH POOL TRIGGER RECEIVER [RETIRED_TRIGGER RETIRED_RECEIVER]
#   RETIRED_* default to their existing anchored values, then to the zero-address fail-closed stub.
#   The CRE workflow id is NOT here: one consolidated workflow serves every lane, so its
#   &creWorkflowId pin lives once in config/state/common.deployed.yaml (`just record-cre-workflow-id`).
#   env DEPLOYED_YAML_GENERATOR — the recipe named in the generated header (default "just deploy-test").
#   `just deploy-automation` sets it, because a pair-only redeploy produces this file too and the header
#   must name the recipe that actually wrote it rather than the one that first created the lane.
#
# The three L2 addresses are the ONLY contracts this migration deploys (OraclePool, SyncTrigger,
# CREReceiver). The pre-existing CustomSender
# proxy/impl + ProxyAdmin are NOT here: they are fixed external
# facts pinned in config/state/<net>.inputs.yaml (externals:), cross-checked by verify-constants-sync.
# Every value is validated as a non-zero 0x+40hex address and checksummed before writing — the
# state-mate `.deployed` loader rejects `null`/placeholder, so we fail early here with a clear message.
set -euo pipefail

if [[ "$#" -ne 4 && "$#" -ne 6 ]]; then
  echo "write-deployed-yaml: expected 4 or 6 args (OUT POOL TRIGGER RECEIVER [RETIRED_TRIGGER RETIRED_RECEIVER]), got $#" >&2
  exit 1
fi
command -v cast >/dev/null 2>&1 || { echo "write-deployed-yaml: missing required command: cast" >&2; exit 1; }

out="$1"
retired_trigger="${5:-}"
retired_receiver="${6:-}"
if [[ -z "$retired_trigger" && -f "$out" ]]; then
  retired_trigger="$(sed -nE 's/^[[:space:]]*-[[:space:]]*&RETIRED_l2SyncTrigger[[:space:]]+"(0x[0-9a-fA-F]{40})".*/\1/p' "$out" | head -n1)"
fi
if [[ -z "$retired_receiver" && -f "$out" ]]; then
  retired_receiver="$(sed -nE 's/^[[:space:]]*-[[:space:]]*&RETIRED_l2CreReceiver[[:space:]]+"(0x[0-9a-fA-F]{40})".*/\1/p' "$out" | head -n1)"
fi
retired_trigger="${retired_trigger:-0x0000000000000000000000000000000000000000}"
retired_receiver="${retired_receiver:-0x0000000000000000000000000000000000000000}"
for retired in "$retired_trigger" "$retired_receiver"; do
  if [[ ! "$retired" =~ ^0x[0-9a-fA-F]{40}$ ]]; then
    echo "write-deployed-yaml: retired address is not 0x + 40 hex chars: '$retired'" >&2
    exit 1
  fi
done

shift
labels=(l2OraclePool l2SyncTrigger l2CreReceiver)
addrs=("${@:1:3}")

declare -a checksummed
for i in "${!addrs[@]}"; do
  a="${addrs[$i]}"
  if [[ ! "$a" =~ ^0x[0-9a-fA-F]{40}$ || "$a" == 0x0000000000000000000000000000000000000000 ]]; then
    echo "write-deployed-yaml: ${labels[$i]} is not a valid non-zero address: '${a:-<unset>}'" >&2
    exit 1
  fi
  checksummed[$i]="$(cast to-check-sum-address "$a")"
done

# Stamp the deploy commit as a COMMENT — state-mate's .deployed loader accepts only the `deployed:`
# section, so a real key would be rejected. Records which tree produced the on-chain bytecode (audit
# trail; config/diffyscan/l2-<net>.yaml pins the same commit for source diffs). If the sources that
# land in the deployed contracts are dirty at deploy time the stamp won't match what was deployed,
# so append a "-dirty" suffix. Scope the check to what actually affects the deployed sources —
# src/, lib/, and the build config — so unrelated dirt (.env, docs, state config) doesn't force a
# needless dirty stamp. Use `git status --porcelain` (not `git diff`, which misses UNTRACKED source),
# with `:/`-anchored pathspecs so the check is correct from any caller working directory.
deploy_commit="$(git rev-parse HEAD)"
if [[ -n "$(git status --porcelain -- :/src :/lib :/foundry.toml :/remappings.txt)" ]]; then
  echo "write-deployed-yaml: WARNING — source tree dirty at deploy (src/lib/build config); stamping deploy-commit '-dirty'" >&2
  deploy_commit="${deploy_commit}-dirty"
fi

{
  echo "---"
  echo "# GENERATED by '${DEPLOYED_YAML_GENERATOR:-just deploy-test}' — review and commit alongside the migration; do not hand-edit."
  echo "# The three Stage-1 deploy outputs (OraclePool, SyncTrigger, CREReceiver) — the only contracts this"
  echo "# migration deploys. The two RETIRED_* anchors preserve the superseded automation pair. The"
  echo "# pre-existing CustomSender proxy/impl + ProxyAdmin are external facts in"
  echo "# config/state/<net>.inputs.yaml (externals:), NOT here; the shared CRE workflow id (deployed.l1) is in"
  echo "# config/state/common.deployed.yaml. state-mate merges both deployed files (anchors first) ahead of"
  echo "# the shared wiring l2.yaml so the *aliases resolve."
  echo "# deploy-commit: $deploy_commit"
  echo "deployed:"
  echo "  l2:"
  for i in "${!labels[@]}"; do
    printf '    - &%s "%s"\n' "${labels[$i]}" "${checksummed[$i]}"
  done
  printf '    - &RETIRED_l2SyncTrigger "%s"\n' "$retired_trigger"
  printf '    - &RETIRED_l2CreReceiver "%s"\n' "$retired_receiver"
} > "$out"

echo "Wrote $out"
