#!/usr/bin/env bash
# Emit a state-mate `<net>.deployed.yaml` sibling from resolved deployed addresses.
#
# Usage: write-deployed-yaml.sh OUT_PATH SENDER IMPL PROXY POOL TRIGGER RECEIVER
#
# The six addresses map 1:1 to the anchors the wiring `<net>.yaml` references. Every value is
# validated as a non-zero 0x+40hex address and checksummed before writing — the state-mate
# `.deployed` loader rejects `null`/placeholder, so we fail early here with a clear message.
set -euo pipefail

if [[ "$#" -ne 7 ]]; then
  echo "write-deployed-yaml: expected 7 args (OUT SENDER IMPL PROXY POOL TRIGGER RECEIVER), got $#" >&2
  exit 1
fi
command -v cast >/dev/null 2>&1 || { echo "write-deployed-yaml: missing required command: cast" >&2; exit 1; }

out="$1"; shift
labels=(l2CustomSender l2CustomSenderImpl l2ProxyAdmin l2OraclePool l2SyncTrigger l2CreReceiver)
addrs=("$@")

declare -a checksummed
for i in "${!addrs[@]}"; do
  a="${addrs[$i]}"
  if [[ ! "$a" =~ ^0x[0-9a-fA-F]{40}$ || "$a" == 0x0000000000000000000000000000000000000000 ]]; then
    echo "write-deployed-yaml: ${labels[$i]} is not a valid non-zero address: '${a:-<unset>}'" >&2
    exit 1
  fi
  checksummed[$i]="$(cast to-check-sum-address "$a")"
done

{
  echo "---"
  echo "# GENERATED by 'just deploy-stage1' — review and commit alongside the migration; do not hand-edit."
  echo "# Our deployed contracts: pre-existing CustomSender proxy/impl + ProxyAdmin, and the Stage-1"
  echo "# deploy outputs (OraclePool, SyncTrigger, CREReceiver). state-mate concatenates this file"
  echo "# (anchors first) ahead of the wiring <net>.yaml so the *aliases resolve."
  echo "# WARNING: cross-chain address reuse — a hex here can be a DIFFERENT contract on another chain"
  echo "#   (deterministic deploys; e.g. l2CustomSender == an L1 adapter). Reuse map: docs/audit-scope.md."
  echo "deployed:"
  echo "  l1: [] # L2 configs check no L1 contracts (the L1 receiver is verified by l1-mainnet.yaml)."
  echo "  l2:"
  for i in "${!labels[@]}"; do
    printf '    - &%s "%s"\n' "${labels[$i]}" "${checksummed[$i]}"
  done
} > "$out"

echo "Wrote $out"
